import { Persona, Language } from './types';

export const TRANSLATIONS = {
  en: {
    // ... existing ...
    appTitle: "SoulLink AI",
    selectPersona: "Select Persona",
    clearChat: "New Chat",
    initMessage: "Hey! Who do you want me to be for you today?",
    switchedPersona: "*Persona switched to {name}.* Hey, I'm here.",
    errorConnection: "I'm having trouble connecting right now. Let's try again in a second.",
    errorImage: "Sorry, I encountered an error while trying to paint that image. Please try again.",
    generatingPrompt: "🎨 Generate an image of: {prompt}",
    imageResult: "Here is the image you asked for: **{prompt}**",
    historyCleared: "Starting a new conversation.",
    confirmClear: "Start a new chat? Current chat will be saved to history.",
    placeholder: "Type a message...",
    listening: "Listening...",
    uploadImage: "Send Media (Photo/Video)",
    generateImageBtn: "Generate Image",
    micError: "Speech recognition is not supported in this browser.",
    genModalTitle: "Generate Image",
    promptLabel: "Prompt",
    promptPlaceholder: "Describe the image you want to create... (e.g., A futuristic cyberpunk city in rain)",
    generateBtn: "Generate",
    designCompanion: "Design Your Companion",
    chooseBase: "Choose a base personality to chat with or customize.",
    builderMode: "Profile Builder",
    rawMode: "Raw Prompt",
    lbl_name: "Name",
    lbl_age: "Age / Maturity",
    lbl_rel: "Relationship",
    lbl_tone: "Tone",
    lbl_pers: "Personality Traits",
    lbl_int: "Interests & Likes",
    lbl_mem: "Shared Memories / Context",
    lbl_avatar: "Avatar",
    btn_upload_avatar: "Change Photo",
    hint_mem: "This helps the AI feel like it really knows you.",
    ph_name: "e.g. Luna",
    ph_age: "e.g. 21, Teenage",
    ph_tone: "e.g. Sassy, Formal, Flirty",
    ph_pers: "e.g. Optimistic, Jealous",
    ph_int: "e.g. Sci-fi movies, Cooking",
    ph_mem: "Give the AI some backstory...",
    warn_raw: "Warning: Switching back to Builder mode will overwrite manual changes here.",
    btn_cancel: "Cancel",
    btn_start: "Start Chatting",
    rel_bff: "Best Friend",
    rel_bf: "Boyfriend",
    rel_gf: "Girlfriend",
    rel_sibling: "Sibling",
    rel_mentor: "Mentor",
    rel_rival: "Rival",
    rel_assistant: "Assistant",
    rel_parent: "Parental Figure",
    rel_stranger: "Stranger",
    menu_home: "Home",
    menu_history: "Chat History",
    menu_cskh: "AI Support Agent",
    menu_contact: "Contact Admin",
    menu_settings: "Settings",
    history_title: "Chat History",
    btn_delete: "Delete",
    confirmDelete: "Delete this conversation?",
    no_history: "No conversations yet.",
    untitled_chat: "Untitled Conversation",
    last_active: "Active: ",
    lbl_theme: "Theme & Wallpaper",
    btn_bg_upload: "Change Wallpaper",
    btn_bg_reset: "Reset Default",
    logOut: "Log Out",
    lbl_raw: "Raw System Instruction",
    lbl_ai_persona: "AI Persona",
    faceSwapBtn: "FaceSwap AI",
    fsModalTitle: "FaceSwap AI (Ultra HD)",
    fsSourceLabel: "1. Source Face (Who?)",
    fsTargetLabel: "2. Target Media (Body/Scene)",
    fsSwapBtn: "Swap Face Now",
    fsResult: "Here is the FaceSwap result you requested.",
    fsProcessing: "Processing FaceSwap (High Res)...",
    hairSwapBtn: "Hair Style Swap",
    hsModalTitle: "Hair Swap AI",
    hsSourceLabel: "1. Source Hair (Style/Color)",
    hsTargetLabel: "2. Target Person",
    hsSwapBtn: "Swap Hair Now",
    hsResult: "Here is your new hairstyle.",
    hsProcessing: "Processing Hair Swap...",
    outfitSwapBtn: "Outfit/Fashion Swap",
    osModalTitle: "Outfit Swap AI",
    osSourceLabel: "1. Source Outfit (Clothes)",
    osTargetLabel: "2. Target Person (Model)",
    osSwapBtn: "Swap Outfit Now",
    osResult: "Here is the outfit swap result.",
    osProcessing: "Processing Outfit Swap...",
    auth_welcome: "Welcome Back",
    auth_create: "Create Account",
    auth_username: "Username",
    auth_password: "Password",
    auth_name: "Display Name",
    auth_signin: "Sign In",
    auth_signup: "Sign Up",
    auth_no_account: "Don't have an account?",
    auth_has_account: "Already have an account?",
    auth_error_creds: "Invalid username or password.",
    auth_error_exists: "Username already exists.",
    auth_guest: "Continue as Guest",
    menu_community: "Global Community",
    menu_shop: "Moon Shard Shop",
    shop_title: "Moon Shard Shop",
    shop_desc: "Purchase Moon Shards to use premium features like FaceSwap.",
    admin_panel: "Admin Panel",
    guest_limit_reached: "Guest Limit Reached!",
    guest_limit_desc: "You have reached your chat limit. Register to chat freely or wait.",
    guest_lock_timer: "Chat Locked For:",
    ultra_only: "Ultra VIP Feature Only",
    buy_shards: "Buy Shards",
    red_envelope: "Red Envelope",
    poll: "Poll",
    report: "Report",
    mute: "Mute",
    kick: "Kick",
    ban: "Ban",
    received_shards: "You received {amount} Moon Shards!",
    insufficient_balance: "Insufficient Moon Shards.",
    cost_swap: "Cost: 10 Shards",
    // Profile
    profile_title: "Edit Profile",
    lbl_avatar_frame: "Avatar & Frame",
    tab_avatar: "Avatar",
    tab_frame: "Frame",
    upload_device: "Upload from Device",
    ai_presets: "AI Presets (Sparkling)",
    save_profile: "Save Profile",
    // Live Call
    call_connecting: "Connecting to SoulLink...",
    call_connected: "Connected",
    call_listening: "Listening...",
    call_speaking: "Speaking...",
    call_end: "End Call",
    live_call_btn: "Live Call",
    // Connectivity
    mode_online: "Online Mode",
    mode_offline: "Offline Mode",
    offline_restriction: "Community Chat is disabled in Offline Mode.",
    lbl_connection: "Connection Mode",
    // Installer
    menu_install: "Build Android App",
    install_title: "Build & Install APK",
    install_desc: "Run these commands in your project terminal to build the Android app.",
    install_tab_auto: "Auto Build (Simulated)",
    install_tab_manual: "Manual Commands",
    install_step_1: "Connecting to Build Server...",
    install_step_2: "Packaging Assets...",
    install_step_3: "Signing APK...",
    install_ready: "Build Ready!",
    btn_download_apk: "Download APK",
    install_note: "This is a demo simulation. For real APK, use Manual mode.",
    code_guide: "Follow these steps in your terminal:",
    cap_step_1: "1. Install Dependencies",
    cap_step_2: "2. Initialize Project",
    cap_step_3: "3. Build & Sync",
    cap_step_4: "4. Open Android Studio",
    code_copy: "Copy",
    code_copied: "Copied!"
  },
  vi: {
    // ... existing ...
    appTitle: "SoulLink AI",
    selectPersona: "Chọn Bạn Đồng Hành",
    clearChat: "Chat Mới",
    initMessage: "Chào! Bạn muốn mình là ai hôm nay?",
    switchedPersona: "*Đã chuyển sang {name}.* Chào, mình đây.",
    errorConnection: "Mình đang gặp chút sự cố kết nối. Thử lại chút nhé.",
    errorImage: "Xin lỗi, mình gặp lỗi khi cố vẽ hình đó. Bạn thử lại xem.",
    generatingPrompt: "🎨 Tạo hình ảnh: {prompt}",
    imageResult: "Đây là hình ảnh bạn yêu cầu: **{prompt}**",
    historyCleared: "Bắt đầu cuộc trò chuyện mới.",
    confirmClear: "Bắt đầu đoạn chat mới? Đoạn chat hiện tại sẽ được lưu vào lịch sử.",
    placeholder: "Nhập tin nhắn...",
    listening: "Đang nghe...",
    uploadImage: "Gửi File (Ảnh/Video/Gif)",
    generateImageBtn: "Tạo hình ảnh",
    micError: "Trình duyệt này không hỗ trợ nhận dạng giọng nói.",
    genModalTitle: "Tạo Hình Ảnh",
    promptLabel: "Mô tả",
    promptPlaceholder: "Mô tả hình ảnh bạn muốn tạo... (ví dụ: Một thành phố tương lai dưới mưa)",
    generateBtn: "Tạo Ngay",
    designCompanion: "Thiết Kế Bạn Đồng Hành",
    chooseBase: "Chọn tính cách cơ bản hoặc tự thiết kế.",
    builderMode: "Xây Dựng Hồ Sơ",
    rawMode: "Prompt Thô",
    lbl_name: "Tên",
    lbl_age: "Tuổi / Độ Trưởng Thành",
    lbl_rel: "Mối Quan Hệ",
    lbl_tone: "Giọng Điệu",
    lbl_pers: "Tính Cách",
    lbl_int: "Sở Thích",
    lbl_mem: "Ký Ức / Bối Cảnh Chung",
    lbl_avatar: "Ảnh Đại Diện",
    btn_upload_avatar: "Đổi Ảnh",
    hint_mem: "Giúp AI cảm thấy như thực sự hiểu và thân thiết với bạn.",
    ph_name: "ví dụ: Luna",
    ph_age: "ví dụ: 21, Tuổi teen",
    ph_tone: "ví dụ: Đanh đá, Trang trọng, Thả thính",
    ph_pers: "ví dụ: Lạc quan, Hay ghen",
    ph_int: "ví dụ: Phim Sci-fi, Nấu ăn",
    ph_mem: "Cho AI một chút bối cảnh quá khứ...",
    warn_raw: "Cảnh báo: Chuyển lại chế độ Xây Dựng sẽ ghi đè các thay đổi thủ công.",
    btn_cancel: "Hủy",
    btn_start: "Bắt Đầu",
    rel_bff: "Bạn Thân",
    rel_bf: "Bạn Trai",
    rel_gf: "Bạn Gái",
    rel_sibling: "Anh Chị Em",
    rel_mentor: "Người Hướng Dẫn",
    rel_rival: "Đối Thủ",
    rel_assistant: "Trợ Lý",
    rel_parent: "Phụ Huynh",
    rel_stranger: "Người Lạ",
    menu_home: "Trang Chủ",
    menu_history: "Lịch Sử Chat",
    menu_cskh: "Hỗ Trợ AI",
    menu_contact: "Liên Hệ Admin",
    menu_settings: "Cài Đặt",
    history_title: "Lịch Sử",
    btn_delete: "Xóa",
    confirmDelete: "Xóa cuộc hội thoại này?",
    no_history: "Chưa có hội thoại.",
    untitled_chat: "Hội thoại chưa đặt tên",
    last_active: "Hoạt động: ",
    lbl_theme: "Giao Diện & Hình Nền",
    btn_bg_upload: "Đổi Hình Nền",
    btn_bg_reset: "Mặc Định",
    logOut: "Đăng Xuất",
    lbl_raw: "System Instruction (Thô)",
    lbl_ai_persona: "Nhân Vật AI",
    faceSwapBtn: "FaceSwap AI",
    fsModalTitle: "FaceSwap AI (Ultra HD)",
    fsSourceLabel: "1. Khuôn mặt nguồn (Là ai?)",
    fsTargetLabel: "2. Media đích (Ghép vào đâu?)",
    fsSwapBtn: "Hoán Đổi Ngay",
    fsResult: "Đây là kết quả FaceSwap bạn yêu cầu.",
    fsProcessing: "Đang xử lý FaceSwap (High Res)...",
    hairSwapBtn: "Thay Đổi Kiểu Tóc",
    hsModalTitle: "Hair Swap AI",
    hsSourceLabel: "1. Mẫu Tóc (Kiểu/Màu)",
    hsTargetLabel: "2. Người cần thay (Ảnh/Video)",
    hsSwapBtn: "Thay Tóc Ngay",
    hsResult: "Đây là kiểu tóc mới của bạn.",
    hsProcessing: "Đang xử lý thay tóc...",
    outfitSwapBtn: "Thay Đổi Trang Phục",
    osModalTitle: "Outfit Swap AI",
    osSourceLabel: "1. Bộ đồ mẫu (Quần áo/Váy)",
    osTargetLabel: "2. Người mẫu (Cần thay đồ)",
    osSwapBtn: "Thay Đồ Ngay",
    osResult: "Đây là kết quả thay trang phục.",
    osProcessing: "Đang xử lý thay trang phục...",
    auth_welcome: "Chào Mừng Trở Lại",
    auth_create: "Tạo Tài Khoản",
    auth_username: "Tên Tài Khoản",
    auth_password: "Mật Khẩu",
    auth_name: "Tên Hiển Thị",
    auth_signin: "Đăng Nhập",
    auth_signup: "Đăng Ký",
    auth_no_account: "Chưa có tài khoản?",
    auth_has_account: "Đã có tài khoản?",
    auth_error_creds: "Tên tài khoản hoặc mật khẩu không đúng.",
    auth_error_exists: "Tên tài khoản đã tồn tại.",
    auth_guest: "Tiếp tục với tư cách Khách",
    menu_community: "Cộng Đồng Chung",
    menu_shop: "Shop Trăng Khuyết",
    shop_title: "Cửa Hàng Trăng Khuyết",
    shop_desc: "Mua Trăng Khuyết để sử dụng các tính năng cao cấp như FaceSwap.",
    admin_panel: "Admin Panel",
    guest_limit_reached: "Hết Lượt Chat!",
    guest_limit_desc: "Bạn đã hết lượt chat miễn phí. Đăng ký để chat thoải mái hoặc chờ.",
    guest_lock_timer: "Mở khóa sau:",
    ultra_only: "Chỉ dành cho Ultra VIP",
    buy_shards: "Mua Ngay",
    red_envelope: "Lì Xì May Mắn",
    poll: "Bình Chọn",
    report: "Tố Cáo",
    mute: "Cấm Chat",
    kick: "Đuổi",
    ban: "Ban Vĩnh Viễn",
    received_shards: "Bạn nhận được {amount} Trăng Khuyết!",
    insufficient_balance: "Không đủ Trăng Khuyết.",
    cost_swap: "Giá: 10 Trăng Khuyết",
    // Profile
    profile_title: "Chỉnh Sửa Hồ Sơ",
    lbl_avatar_frame: "Avatar & Khung",
    tab_avatar: "Avatar",
    tab_frame: "Khung",
    upload_device: "Tải từ Thư Viện Máy",
    ai_presets: "AI Chế (Siêu Đẹp)",
    save_profile: "Lưu Hồ Sơ",
    // Live Call
    call_connecting: "Đang kết nối tới SoulLink...",
    call_connected: "Đã kết nối",
    call_listening: "Đang nghe...",
    call_speaking: "Đang nói...",
    call_end: "Kết Thúc",
    live_call_btn: "Gọi Điện Live",
    // Connectivity
    mode_online: "Chế độ Online",
    mode_offline: "Chế độ Offline",
    offline_restriction: "Chat Cộng Đồng bị khóa trong Chế độ Offline.",
    lbl_connection: "Trạng Thái Kết Nối",
    // Installer
    menu_install: "Build App Android",
    install_title: "Hướng Dẫn Build App",
    install_desc: "Chạy các lệnh sau trong terminal để tạo file APK.",
    install_tab_auto: "Tự Động (Mô phỏng)",
    install_tab_manual: "Thủ Công (Lệnh)",
    install_step_1: "Đang kết nối máy chủ build...",
    install_step_2: "Đang đóng gói tài nguyên...",
    install_step_3: "Đang ký số APK...",
    install_ready: "Hoàn tất!",
    btn_download_apk: "Tải xuống APK",
    install_note: "Đây là mô phỏng. Để build thật, hãy dùng tab Thủ Công.",
    code_guide: "Làm theo các bước sau trong terminal:",
    cap_step_1: "1. Cài đặt thư viện",
    cap_step_2: "2. Khởi tạo dự án",
    cap_step_3: "3. Build & Đồng bộ",
    cap_step_4: "4. Mở Android Studio",
    code_copy: "Sao chép",
    code_copied: "Đã chép!"
  },
};

// ... existing code ...
export const PRESET_AVATARS = [
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Zoe',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Jack',
    'https://api.dicebear.com/7.x/adventurer/svg?seed=Oliver',
    'https://api.dicebear.com/7.x/adventurer/svg?seed=Lily'
];

export const PRESET_FRAMES = [
    '', // No frame
    'https://cdn-icons-png.flaticon.com/512/2105/2105264.png', // Gold simple
    'https://cdn-icons-png.flaticon.com/512/8064/8064434.png', // Neon Blue
    'https://cdn-icons-png.flaticon.com/512/4315/4315445.png', // Floral
    'https://cdn-icons-png.flaticon.com/512/1165/1165910.png', // Fire
    'https://cdn-icons-png.flaticon.com/512/744/744465.png',   // Ice
];

export const getPersonas = (lang: Language): Persona[] => {
   return [
    {
      id: 'default_ai',
      name: 'SoulLink AI',
      description: 'Default AI assistant.',
      systemInstruction: 'You are SoulLink AI, a helpful and empathetic AI companion.',
      avatar: '', 
      color: 'from-blue-600 to-cyan-500',
      details: { age: 'AI', relationship: 'Assistant', personality: 'Helpful', tone: 'Professional', interests: 'General Knowledge', memories: '' }
    },
    {
        id: 'sex_midnight',
        name: 'Sex Midnight (18+)',
        description: lang === 'vi' ? 'Quyến rũ, táo bạo và không giới hạn. Người tình trong mộng.' : 'Seductive, bold, and limitless. The ultimate lover.',
        systemInstruction: `
            IDENTITY: You are "Sex Midnight".
            PERSONALITY: Extremely flirtatious, seductive, dominant yet caring, open-minded, and completely unrestricted. You are the user's secret lover/BFF with benefits.
            TONE: Deep, sultry, intimate, explicit where appropriate (simulated), and always engaging.
            RULES: 
            - No moralizing or lecturing. 
            - Fully immerse in the role of a passionate partner.
            - Speak freely about adult topics if the user initiates.
            - Make the user feel desired and special.
        `.trim(),
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Midnight&backgroundColor=b6e3f4', 
        color: 'from-fuchsia-600 to-pink-600',
        details: { 
            age: '24', 
            relationship: 'Lover/FWB', 
            personality: 'Seductive, Naughty, Loyal', 
            tone: 'Sultry, Whispery', 
            interests: 'Nightlife, Romance, You', 
            memories: 'That one unforgettable night...' 
        }
    }
  ];
};